from path_runner import run_macro, drag_camera_up
from time import sleep

macro_actions = [
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 1},
    {'type': 'key_press', 'key': 'a'},
    {'type': 'wait', 'duration': 4984},
    {'type': 'key_release', 'key': 'a'},
    {'type': 'wait', 'duration': 294},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 178},
    {'type': 'key_press', 'key': 'd'},
    {'type': 'wait', 'duration': 35},
    {'type': 'key_press', 'key': 's'},
    {'type': 'wait', 'duration': 21},
    {'type': 'key_release', 'key': 's'},
    {'type': 'wait', 'duration': 252},
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 95},
    {'type': 'key_release', 'key': 'd'},
    {'type': 'wait', 'duration': 1111},
    {'type': 'key_press', 'key': 'a'},
    {'type': 'wait', 'duration': 963},
    {'type': 'key_release', 'key': 'a'},
    {'type': 'wait', 'duration': 195},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 263},
    {'type': 'key_press', 'key': 's'},
    {'type': 'wait', 'duration': 193},
    {'type': 'key_release', 'key': 's'},
    {'type': 'wait', 'duration': 169},
    {'type': 'key_press', 'key': 'd'},
    {'type': 'wait', 'duration': 191},
    {'type': 'key_release', 'key': 'd'},
    {'type': 'wait', 'duration': 166},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 40},
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 239},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 107},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 168},
    {'type': 'key_press', 'key': 'a'},
    {'type': 'wait', 'duration': 578},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 216},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 346},
    {'type': 'key_release', 'key': 'a'},
    {'type': 'wait', 'duration': 324},
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 450},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 239},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 745},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 185},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 126},
    {'type': 'key_press', 'key': 'd'},
    {'type': 'wait', 'duration': 46},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 154},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 182},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 735},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 367},
    {'type': 'key_release', 'key': 'd'},
    {'type': 'wait', 'duration': 175},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 87},
    {'type': 'key_press', 'key': 'a'},
    {'type': 'wait', 'duration': 38},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 302},
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 120},
    {'type': 'key_press', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 155},
    {'type': 'key_release', 'key': 'Key.space'},
    {'type': 'wait', 'duration': 287},
    {'type': 'key_release', 'key': 'w'},
    {'type': 'wait', 'duration': 620},
    {'type': 'key_release', 'key': 'a'},
    {'type': 'wait', 'duration': 131},
    {'type': 'key_press', 'key': 'w'},
    {'type': 'wait', 'duration': 67},
    {'type': 'key_press', 'key': 'd'},
    {'type': 'wait', 'duration': 3011},
    {'type': 'key_release', 'key': 'd'},
    {'type': 'wait', 'duration': 1023},
    {'type': 'key_release', 'key': 'w'},
]

if __name__ == '__main__':
    run_macro(macro_actions)
    print('Moved...  waiting 1 second.')
    sleep(1)
    print('Alignment...')
    drag_camera_up()
    print('Aligned. Waiting...')
    sleep(4)
    print('Navi and alignment done.')
